# Generated by Django 5.2.12 on 2026-03-04 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='policy.policycategory')),
            ],
            options={
                'verbose_name_plural': 'Policy Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Full policy content')),
                ('category_type', models.CharField(choices=[('governance', 'Governance'), ('compliance', 'Compliance'), ('risk_management', 'Risk Management'), ('financial', 'Financial'), ('operational', 'Operational'), ('ethical', 'Ethical'), ('safety', 'Safety'), ('environmental', 'Environmental'), ('other', 'Other')], default='governance', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Date when policy becomes effective', null=True)),
                ('review_date', models.DateField(blank=True, help_text='Next review date', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when policy expires', null=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('board', 'Board Only'), ('committee', 'Committee'), ('management', 'Management'), ('restricted', 'Restricted')], default='board', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='policies/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('policy_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='policy.policy')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.policycategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_type', models.CharField(choices=[('scheduled', 'Scheduled Review'), ('ad_hoc', 'Ad Hoc Review'), ('compliance', 'Compliance Review'), ('incident', 'Incident Review')], max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('action_required', models.BooleanField(default=False)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='policy.policy')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='policy.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('policy', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status', 'is_current'], name='policy_poli_status_c1d7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['category_type'], name='policy_poli_categor_c35bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['effective_date'], name='policy_poli_effecti_5f0234_idx'),
        ),
    ]
