# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyExpiryMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(help_text='Date when policy expires')),
                ('notification_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent_30_days', 'Sent 30 Days Before'), ('sent_14_days', 'Sent 14 Days Before'), ('sent_7_days', 'Sent 7 Days Before'), ('sent_1_day', 'Sent 1 Day Before'), ('expired', 'Expired')], default='not_sent', max_length=20)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveIntegerField(default=0, help_text='Number of notifications sent')),
                ('action_taken', models.TextField(blank=True, help_text='Actions taken in response to expiry')),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether expiry has been addressed')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how expiry was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_expiry_actions', to=settings.AUTH_USER_MODEL)),
                ('notified_users', models.ManyToManyField(blank=True, related_name='policy_expiry_notifications', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_monitors', to='policy.policy')),
            ],
            options={
                'verbose_name': 'Policy Expiry Monitor',
                'verbose_name_plural': 'Policy Expiry Monitors',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='policy_poli_expiry__b5a83e_idx'), models.Index(fields=['notification_status'], name='policy_poli_notific_036f5a_idx'), models.Index(fields=['is_resolved'], name='policy_poli_is_reso_ba125a_idx')],
                'unique_together': {('policy', 'expiry_date')},
            },
        ),
    ]
