# Generated by Django 5.2.12 on 2026-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_timezone',
            field=models.CharField(choices=[('Africa/Cairo', 'Egypt (EET, UTC+2)'), ('Europe/Paris', 'France / CET (UTC+1)'), ('Africa/Accra', 'Ghana (GMT, UTC+0)'), ('Asia/Kolkata', 'India (IST, UTC+5:30)'), ('Africa/Nairobi', 'Kenya / Uganda / Tanzania (EAT, UTC+3)'), ('Indian/Mauritius', 'Mauritius (MUT, UTC+4)'), ('Africa/Lagos', 'Nigeria (WAT, UTC+1)'), ('Africa/Johannesburg', 'South Africa (SAST, UTC+2)'), ('Asia/Dubai', 'UAE (GST, UTC+4)'), ('UTC', 'UTC'), ('Africa/Kampala', 'Uganda (EAT, UTC+3)'), ('Europe/London', 'United Kingdom (GMT/BST)')], default='Africa/Nairobi', help_text='Your local timezone — meeting times will be displayed in this timezone.', max_length=60),
        ),
    ]
