# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_preferred_language'),
        ('agencies', '0002_alter_branch_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the user was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who deleted this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this user has been soft-deleted'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Committee name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Committee purpose and responsibilities')),
                ('meeting_type', models.CharField(choices=[('board', 'Board Meeting'), ('audit', 'Audit Committee'), ('risk', 'Risk Committee'), ('governance', 'Governance Committee'), ('executive', 'Executive Committee'), ('nominating', 'Nominating Committee'), ('remuneration', 'Remuneration Committee'), ('other', 'Other')], default='board', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this committee is currently active')),
                ('meeting_frequency', models.CharField(blank=True, help_text="How often this committee meets (e.g., 'Monthly', 'Quarterly')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this committee belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_committees', to='agencies.branch')),
                ('chairperson', models.ForeignKey(blank=True, help_text='Committee chairperson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('chair', 'Chairperson'), ('vice_chair', 'Vice Chairperson'), ('secretary', 'Secretary'), ('member', 'Member'), ('observer', 'Observer')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When user joined the committee')),
                ('left_at', models.DateTimeField(blank=True, help_text='When user left the committee (if applicable)', null=True)),
                ('appointment_date', models.DateField(blank=True, help_text='Date of official appointment', null=True)),
                ('has_voting_rights', models.BooleanField(default=True, help_text='Whether this member can vote')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this membership')),
                ('appointed_by', models.ForeignKey(blank=True, help_text='Who appointed this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_committee_memberships', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_memberships', to='accounts.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee', 'role', 'user'],
            },
        ),
        migrations.CreateModel(
            name='FieldEditPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Django model name (e.g., 'User', 'Meeting')", max_length=100)),
                ('field_name', models.CharField(help_text='Field name to restrict', max_length=100)),
                ('allowed_roles', models.JSONField(default=list, help_text="List of roles that can edit this field (e.g., ['it_administrator', 'company_secretary'])")),
                ('freeze_condition', models.CharField(choices=[('status', 'Freeze on Status'), ('date', 'Freeze After Date'), ('never', 'Never Freeze'), ('always', 'Always Read-Only')], default='never', help_text='When to freeze this field from editing', max_length=20)),
                ('freeze_on_status', models.CharField(blank=True, help_text="Status value that triggers freeze (e.g., 'approved', 'published')", max_length=50)),
                ('freeze_after_date', models.DateTimeField(blank=True, help_text='Date after which field becomes read-only', null=True)),
                ('freeze_after_days', models.PositiveIntegerField(blank=True, help_text='Days after creation/edit after which field freezes', null=True)),
                ('require_approval', models.BooleanField(default=False, help_text='Whether editing this field requires approval')),
                ('description', models.TextField(blank=True, help_text='Description of this restriction')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Edit Permission',
                'verbose_name_plural': 'Field Edit Permissions',
                'ordering': ['model_name', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_user_id', models.UUIDField(help_text='Original user ID before archiving')),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text="User's role at time of termination", max_length=50)),
                ('termination_reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('death', 'Death'), ('contract_end', 'Contract Ended'), ('other', 'Other')], max_length=50)),
                ('termination_notes', models.TextField(blank=True, help_text='Additional notes about termination')),
                ('terminated_at', models.DateTimeField(auto_now_add=True, help_text='When the account was terminated')),
                ('archived_data', models.JSONField(default=dict, help_text='Snapshot of user data at termination time')),
                ('retention_period_years', models.PositiveIntegerField(default=7, help_text='Years to retain this archive')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this archive can be permanently deleted', null=True)),
                ('terminated_by', models.ForeignKey(help_text='Administrator who terminated this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Archive',
                'verbose_name_plural': 'User Archives',
                'ordering': ['-terminated_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookmark_type', models.CharField(choices=[('meeting', 'Meeting'), ('document', 'Document'), ('motion', 'Motion'), ('policy', 'Policy'), ('risk', 'Risk Assessment'), ('committee', 'Committee'), ('annual_meeting', 'Annual Meeting'), ('report', 'Report'), ('other', 'Other')], max_length=50)),
                ('target_id', models.UUIDField(help_text='ID of the bookmarked item')),
                ('target_url', models.CharField(help_text='URL to access the bookmarked item', max_length=500)),
                ('title', models.CharField(help_text='Display title for the bookmark', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('folder', models.CharField(blank=True, help_text='Folder/category for organizing bookmarks', max_length=100)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of bookmarks list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_bo_user_id_bc6916_idx'), models.Index(fields=['bookmark_type'], name='accounts_bo_bookmar_261fbc_idx'), models.Index(fields=['folder'], name='accounts_bo_folder_6cd551_idx'), models.Index(fields=['is_pinned'], name='accounts_bo_is_pinn_fc43fb_idx')],
                'unique_together': {('user', 'bookmark_type', 'target_id')},
            },
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['is_active'], name='accounts_co_is_acti_8c8b89_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['meeting_type'], name='accounts_co_meeting_17230e_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['branch'], name='accounts_co_branch__034d29_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['user', 'is_active'], name='accounts_co_user_id_27f050_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee', 'is_active'], name='accounts_co_committ_30b96c_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['role'], name='accounts_co_role_31784a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('user', 'committee')},
        ),
        migrations.AddIndex(
            model_name='fieldeditpermission',
            index=models.Index(fields=['model_name'], name='accounts_fi_model_n_468800_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldeditpermission',
            index=models.Index(fields=['freeze_condition'], name='accounts_fi_freeze__a466d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldeditpermission',
            index=models.Index(fields=['is_active'], name='accounts_fi_is_acti_bb5981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldeditpermission',
            unique_together={('model_name', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='userarchive',
            index=models.Index(fields=['email'], name='accounts_us_email_43deb8_idx'),
        ),
        migrations.AddIndex(
            model_name='userarchive',
            index=models.Index(fields=['terminated_at'], name='accounts_us_termina_2a10f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userarchive',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_eb33be_idx'),
        ),
    ]
