# Generated by Django 5.2.12 on 2026-03-11 11:12

import apps.esignature.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('drawn', 'Drawn on Signature Pad'), ('uploaded', 'Uploaded Image'), ('typed', 'Typed Signature')], default='drawn', max_length=20)),
                ('image', models.ImageField(upload_to=apps.esignature.models.signature_image_path)),
                ('typed_text', models.CharField(blank=True, max_length=150)),
                ('typed_font', models.CharField(blank=True, default='Dancing Script', max_length=60)),
                ('image_data_uri', models.TextField(blank=True, help_text='Base64 PNG data URI from the signature pad')),
                ('is_default', models.BooleanField(default=False, help_text="User's default/saved signature for future use")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL for one-time external signer signatures', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captured Signature',
                'verbose_name_plural': 'Captured Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignableDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated reference, e.g. ESIG-2025-00042', max_length=60, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('original_file', models.FileField(upload_to=apps.esignature.models.esig_upload_path)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to=apps.esignature.models.signed_upload_path)),
                ('original_hash', models.CharField(blank=True, help_text='SHA-256 of the original file at upload time', max_length=64)),
                ('signed_hash', models.CharField(blank=True, help_text='SHA-256 of the final signed file', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending – Awaiting First Signer'), ('in_progress', 'In Progress'), ('fully_signed', 'Fully Signed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('require_ordered_signing', models.BooleanField(default=True, help_text='Signers must sign in the specified order')),
                ('require_otp', models.BooleanField(default=True, help_text='Each signer must verify via OTP before signing')),
                ('access_level', models.CharField(choices=[('private', 'Private – Signers & Uploader Only'), ('board', 'Board Members'), ('committee', 'Committee Members'), ('restricted', 'Restricted – Named Viewers Only')], default='private', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Document / signing deadline.  NULL = no expiry.', null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalised_at', models.DateTimeField(blank=True, help_text='When the last signature was collected', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signable_documents', to='agencies.branch')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_signable_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signable Document',
                'verbose_name_plural': 'Signable Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentViewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('can_download', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_views', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewable_signable_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='esignature.signabledocument')),
            ],
            options={
                'verbose_name': 'Document Viewer',
                'verbose_name_plural': 'Document Viewers',
            },
        ),
        migrations.CreateModel(
            name='SignerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_name', models.CharField(blank=True, max_length=150)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('signing_order', models.PositiveIntegerField(default=1, help_text='Order in which this person signs (1 = first)')),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver'), ('witness', 'Witness'), ('cc', 'CC / Viewer')], default='signer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('viewed', 'Viewed'), ('otp_verified', 'OTP Verified'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Document cannot be fully signed until this person signs')),
                ('signing_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.JSONField(blank=True, help_text='Where to embed the signature in the PDF', null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True)),
                ('signed_device_info', models.JSONField(blank=True, help_text='Browser, OS, screen size etc captured at signing time', null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='esignature.signabledocument')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for external signers (use email below)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signer Assignment',
                'verbose_name_plural': 'Signer Assignments',
                'ordering': ['document', 'signing_order'],
            },
        ),
        migrations.CreateModel(
            name='ESignatureAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Captured at log time; persists if actor user is later deleted', max_length=254)),
                ('action', models.CharField(choices=[('upload', 'Document Uploaded'), ('view', 'Document Viewed'), ('download', 'Document Downloaded'), ('sign', 'Document Signed'), ('reject', 'Signature Rejected'), ('invite', 'Signer Invited'), ('remind', 'Reminder Sent'), ('revoke', 'Signer Revoked'), ('cancel', 'Document Cancelled'), ('expire', 'Document Expired'), ('otp_request', 'OTP Requested'), ('otp_verify', 'OTP Verified'), ('tamper_detected', 'Tampering Detected')], db_index=True, max_length=20)),
                ('detail', models.TextField(blank=True, help_text='Human-readable detail')),
                ('document_status_before', models.CharField(blank=True, max_length=20)),
                ('document_status_after', models.CharField(blank=True, max_length=20)),
                ('document_hash_snapshot', models.CharField(blank=True, help_text='SHA-256 of the document at this moment', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esig_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='esignature.signabledocument')),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='esignature.signerassignment')),
            ],
            options={
                'verbose_name': 'E-Signature Audit Log',
                'verbose_name_plural': 'E-Signature Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_hash_at_signing', models.CharField(help_text='SHA-256 of the document file at the moment of signing', max_length=64)),
                ('action', models.CharField(choices=[('signed', 'Signed'), ('rejected', 'Rejected')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('otp_used', models.BooleanField(default=False)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_events', to='esignature.capturedsignature')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signing_event', to='esignature.signerassignment')),
            ],
            options={
                'verbose_name': 'Document Signing Event',
                'verbose_name_plural': 'Document Signing Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SigningOTPRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='esignature.signerassignment')),
            ],
            options={
                'verbose_name': 'Signing OTP Record',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signabledocument',
            index=models.Index(fields=['status', '-created_at'], name='esignature__status_fb3a18_idx'),
        ),
        migrations.AddIndex(
            model_name='signabledocument',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='esignature__uploade_60c31d_idx'),
        ),
        migrations.AddIndex(
            model_name='signabledocument',
            index=models.Index(fields=['branch', 'status'], name='esignature__branch__14a0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='signabledocument',
            index=models.Index(fields=['reference_number'], name='esignature__referen_2381bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentviewer',
            unique_together={('document', 'user')},
        ),
        migrations.AddIndex(
            model_name='signerassignment',
            index=models.Index(fields=['status', '-created_at'], name='esignature__status_8e10df_idx'),
        ),
        migrations.AddIndex(
            model_name='signerassignment',
            index=models.Index(fields=['document', 'status'], name='esignature__documen_4cbfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='signerassignment',
            index=models.Index(fields=['signing_token'], name='esignature__signing_a8574c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signerassignment',
            unique_together={('document', 'signing_order')},
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['document', 'timestamp'], name='esignature__documen_4eabcc_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='esignature__actor_i_ab9572_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='esignature__action_74a4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='esignature__ip_addr_2e9ea5_idx'),
        ),
    ]
