# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esignature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentViewingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_identifier', models.CharField(blank=True, help_text='Identifier for viewer (email, IP, etc.) when user is null', max_length=255)),
                ('view_start_time', models.DateTimeField(auto_now_add=True)),
                ('view_end_time', models.DateTimeField(blank=True, null=True)),
                ('view_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('view_mode', models.CharField(choices=[('single_page', 'Single Page'), ('continuous', 'Continuous Scroll'), ('split', 'Split View'), ('fullscreen', 'Fullscreen')], default='single_page', max_length=20)),
                ('zoom_level', models.CharField(choices=[('fit_width', 'Fit Width'), ('fit_page', 'Fit Page'), ('50', '50%'), ('75', '75%'), ('100', '100%'), ('125', '125%'), ('150', '150%'), ('200', '200%')], default='100', max_length=20)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Last page viewed')),
                ('pages_viewed', models.JSONField(default=list, help_text='List of page numbers viewed')),
                ('scroll_events', models.PositiveIntegerField(default=0, help_text='Number of scroll events')),
                ('search_queries', models.JSONField(default=list, help_text='Search queries made during viewing')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, help_text='e.g., desktop, tablet, mobile', max_length=50)),
            ],
            options={
                'verbose_name': 'Document Viewing Session',
                'verbose_name_plural': 'Document Viewing Sessions',
                'ordering': ['-view_start_time'],
            },
        ),
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('comment', 'Comment'), ('bookmark', 'Bookmark'), ('text', 'Text'), ('drawing', 'Drawing'), ('strikeout', 'Strikeout'), ('underline', 'Underline'), ('signature', 'Signature')], max_length=20)),
                ('page_number', models.PositiveIntegerField(help_text='Page number where annotation is placed')),
                ('x_position', models.DecimalField(blank=True, decimal_places=2, help_text='X coordinate', max_digits=10, null=True)),
                ('y_position', models.DecimalField(blank=True, decimal_places=2, help_text='Y coordinate', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width of annotation area', max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height of annotation area', max_digits=10, null=True)),
                ('content', models.TextField(blank=True, help_text='Annotation text or comment')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('black', 'Black'), ('white', 'White')], default='yellow', max_length=20)),
                ('author_identifier', models.CharField(blank=True, help_text='Identifier for author when user is null', max_length=255)),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to author')),
                ('is_resolved', models.BooleanField(default=False, help_text='For comments, whether resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Annotation',
                'verbose_name_plural': 'PDF Annotations',
                'ordering': ['document', 'page_number', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='esignatureauditlog',
            name='esignature__documen_4eabcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='esignatureauditlog',
            name='esignature__actor_i_ab9572_idx',
        ),
        migrations.RemoveIndex(
            model_name='esignatureauditlog',
            name='esignature__action_74a4fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='esignatureauditlog',
            name='esignature__ip_addr_2e9ea5_idx',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='actor_email',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='document_hash_snapshot',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='document_status_after',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='document_status_before',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='esignatureauditlog',
            name='related_assignment',
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='action_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='action_type',
            field=models.CharField(choices=[('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_viewed', 'Document Viewed'), ('signer_added', 'Signer Added'), ('signer_removed', 'Signer Removed'), ('signer_notified', 'Signer Notified'), ('signature_started', 'Signature Started'), ('signature_completed', 'Signature Completed'), ('signature_rejected', 'Signature Rejected'), ('signature_expired', 'Signature Expired'), ('document_completed', 'Document Completed'), ('document_cancelled', 'Document Cancelled'), ('otp_generated', 'OTP Generated'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Verification Failed'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('document_downloaded', 'Document Downloaded'), ('document_printed', 'Document Printed')], default='document_created', max_length=50),
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='actor_identifier',
            field=models.CharField(blank=True, help_text='Identifier for actor (email, IP, etc.) when user is null', max_length=255),
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this log entry has been archived'),
        ),
        migrations.AddField(
            model_name='esignatureauditlog',
            name='retention_until',
            field=models.DateTimeField(blank=True, help_text='Date until which this log must be retained', null=True),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='document_view_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of document viewing in seconds', null=True),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='document_viewed',
            field=models.BooleanField(default=False, help_text='Whether signer has viewed the document'),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='document_viewed_at',
            field=models.DateTimeField(blank=True, help_text='When document was viewed', null=True),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='external_signer_approved',
            field=models.BooleanField(default=False, help_text='Whether external signer has been approved by administrator'),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='external_signer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signerassignment',
            name='external_signer_approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved this external signer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_external_signers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='esignatureauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esignature_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='esignatureauditlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esignature.signabledocument'),
        ),
        migrations.AlterField(
            model_name='esignatureauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signerassignment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Organization member required by default. Leave blank only if external signer approved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['document', '-timestamp'], name='esignature__documen_02c489_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='esignature__action__99efef_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['actor', '-timestamp'], name='esignature__actor_i_a146c1_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['timestamp'], name='esignature__timesta_8a2943_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['is_archived'], name='esignature__is_arch_2b7df2_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureauditlog',
            index=models.Index(fields=['retention_until'], name='esignature__retenti_924cf2_idx'),
        ),
        migrations.AddField(
            model_name='documentviewingsession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_sessions', to='esignature.signabledocument'),
        ),
        migrations.AddField(
            model_name='documentviewingsession',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_viewing_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to='esignature.signabledocument'),
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='viewing_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='esignature.documentviewingsession'),
        ),
        migrations.AddIndex(
            model_name='documentviewingsession',
            index=models.Index(fields=['document', '-view_start_time'], name='esignature__documen_733001_idx'),
        ),
        migrations.AddIndex(
            model_name='documentviewingsession',
            index=models.Index(fields=['viewer', '-view_start_time'], name='esignature__viewer__fba528_idx'),
        ),
        migrations.AddIndex(
            model_name='documentviewingsession',
            index=models.Index(fields=['view_mode'], name='esignature__view_mo_79b5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfannotation',
            index=models.Index(fields=['document', 'page_number'], name='esignature__documen_252f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfannotation',
            index=models.Index(fields=['author'], name='esignature__author__fb75ff_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfannotation',
            index=models.Index(fields=['annotation_type'], name='esignature__annotat_323062_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfannotation',
            index=models.Index(fields=['is_private'], name='esignature__is_priv_2d97df_idx'),
        ),
    ]
