# Generated by Django 5.2.12 on 2026-03-04 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_reference', models.CharField(blank=True, max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Comment',
                'verbose_name_plural': 'Document Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_comment', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTagging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Tagging',
                'verbose_name_plural': 'Document Taggings',
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('action_required', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Workflow',
                'verbose_name_plural': 'Document Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Review'), ('escalated', 'Escalated')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for integrity', max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='is_major_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='permission',
            field=models.CharField(choices=[('view', 'Can View'), ('download', 'Can Download'), ('edit', 'Can Edit'), ('delete', 'Can Delete'), ('share', 'Can Share'), ('comment', 'Can Comment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='activity_type',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('version_created', 'Version Created'), ('comment_added', 'Comment Added'), ('shared', 'Shared')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level'], name='documents_d_access__2eb685_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='documents_d_uploade_2fe388_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['document', 'user'], name='documents_d_documen_fffcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['user', 'permission'], name='documents_d_user_id_2d3e73_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_ef24f6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_252121_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='documents_d_activit_edfb40_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='documents_d_documen_654958_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_by', '-created_at'], name='documents_d_created_acfab9_idx'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttagging',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_taggings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttagging',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_taggings', to='documents.documenttag'),
        ),
        migrations.AddField(
            model_name='documentworkflow',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentworkflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentworkflow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentworkflowaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentworkflowaction',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='documents.documentworkflow'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_cc99c6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_6dba7d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['parent'], name='documents_d_parent__22e0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='documents_d_share_t_57bd35_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_0f1c28_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='documents_d_expires_4b27d0_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttagging',
            index=models.Index(fields=['document'], name='documents_d_documen_1f262c_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttagging',
            index=models.Index(fields=['tag'], name='documents_d_tag_id_16e4cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttagging',
            unique_together={('document', 'tag')},
        ),
        migrations.AddIndex(
            model_name='documentworkflow',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_eec29a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflow',
            index=models.Index(fields=['assigned_to', '-created_at'], name='documents_d_assigne_83c45c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflow',
            index=models.Index(fields=['current_stage'], name='documents_d_current_5b9589_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowaction',
            index=models.Index(fields=['workflow', '-created_at'], name='documents_d_workflo_c78850_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowaction',
            index=models.Index(fields=['actor', '-created_at'], name='documents_d_actor_i_f96759_idx'),
        ),
    ]
