# Generated by Django 5.2.12 on 2026-03-11 09:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique branch code e.g. EN-KE-001', max_length=20, unique=True)),
                ('branch_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('regional_office', 'Regional Office'), ('country_office', 'Country Office'), ('subsidiary', 'Subsidiary Company'), ('affiliate', 'Affiliate'), ('joint_venture', 'Joint Venture'), ('representative_office', 'Representative Office')], default='regional_office', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_review', 'Under Review'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('timezone_name', models.CharField(default='Africa/Nairobi', help_text='IANA timezone name e.g. Europe/London', max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branches/logos/')),
                ('max_users', models.PositiveIntegerField(default=1000, help_text='Maximum number of users for this branch')),
                ('has_own_board', models.BooleanField(default=True, help_text='Branch has its own board of directors')),
                ('reporting_currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('parent_branch', models.ForeignKey(blank=True, help_text='Parent branch if this is a subsidiary of another branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='agencies.branch')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['organization', 'country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code e.g. BOD, AUDIT, RISK', max_length=20)),
                ('committee_type', models.CharField(choices=[('board_of_directors', 'Board of Directors'), ('executive_committee', 'Executive Committee'), ('audit_committee', 'Audit Committee'), ('risk_committee', 'Risk & Compliance Committee'), ('finance_committee', 'Finance Committee'), ('remuneration_committee', 'Remuneration Committee'), ('nomination_committee', 'Nomination Committee'), ('investment_committee', 'Investment Committee'), ('strategy_committee', 'Strategy Committee'), ('governance_committee', 'Governance Committee'), ('technical_committee', 'Technical Committee'), ('special_committee', 'Special / Ad-hoc Committee'), ('subsidiary_board', 'Subsidiary Board'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dissolved', 'Dissolved'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('mandate', models.TextField(blank=True, help_text='Committee mandate and terms of reference')),
                ('quorum_type', models.CharField(choices=[('majority', 'Simple Majority'), ('two_thirds', 'Two-Thirds'), ('three_quarters', 'Three-Quarters'), ('unanimous', 'Unanimous'), ('custom', 'Custom')], default='majority', max_length=20)),
                ('quorum_custom_value', models.PositiveIntegerField(blank=True, help_text='Custom quorum count (used when quorum_type=custom)', null=True)),
                ('min_members', models.PositiveIntegerField(default=3)),
                ('max_members', models.PositiveIntegerField(default=15)),
                ('meeting_frequency', models.CharField(blank=True, help_text='e.g. Monthly, Quarterly, As needed', max_length=50)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Restrict visibility of this committee to its members only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='agencies.branch')),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL)),
                ('parent_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_committees', to='agencies.committee')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarial_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(max_length=254)),
                ('intended_role', models.CharField(choices=[('board_member', 'Board Member'), ('company_secretary', 'Company Secretary'), ('executive_management', 'Executive Management'), ('compliance_officer', 'Compliance Officer'), ('it_administrator', 'IT Administrator'), ('internal_audit', 'Internal Audit')], max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('message', models.TextField(blank=True, help_text='Personal message to include in invitation email')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='agencies.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('intended_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='agencies.committee')),
            ],
            options={
                'verbose_name': 'Branch Invitation',
                'verbose_name_plural': 'Branch Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committee_role', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('observer', 'Observer'), ('advisor', 'Advisor / Consultant'), ('alternate', 'Alternate Member')], default='member', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('term_ended', 'Term Ended')], default='active', max_length=20)),
                ('term_start', models.DateField(default=django.utils.timezone.now)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_current_term', models.BooleanField(default=True)),
                ('has_voting_rights', models.BooleanField(default=True, help_text='Whether this member can vote in committee decisions')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_committee_members', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='agencies.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee', 'committee_role', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('head_office_address', models.TextField(blank=True)),
                ('head_office_country', models.CharField(blank=True, max_length=100)),
                ('head_office_city', models.CharField(blank=True, max_length=100)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agencies.organization'),
        ),
        migrations.CreateModel(
            name='UserBranchMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_role', models.CharField(choices=[('board_member', 'Board Member'), ('company_secretary', 'Company Secretary'), ('executive_management', 'Executive Management'), ('compliance_officer', 'Compliance Officer'), ('it_administrator', 'IT Administrator'), ('internal_audit', 'Internal Audit')], help_text="User's role specifically within this branch", max_length=50)),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('read_only', 'Read Only'), ('limited', 'Limited Access')], default='full', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary branch shown on login and dashboard')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_branch_members', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='agencies.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branch Membership',
                'verbose_name_plural': 'User Branch Memberships',
                'ordering': ['-is_primary', 'branch__name'],
            },
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['branch', 'is_active'], name='agencies_co_branch__e3fd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['committee_type'], name='agencies_co_committ_3c9cbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee', 'is_active'], name='agencies_co_committ_041347_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['user', 'is_active'], name='agencies_co_user_id_0d45f2_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee_role'], name='agencies_co_committ_067c58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('committee', 'user')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'is_active'], name='agencies_br_organiz_3b8674_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['country'], name='agencies_br_country_58bb15_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['branch_type'], name='agencies_br_branch__4614df_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchmembership',
            index=models.Index(fields=['user', 'is_active'], name='agencies_us_user_id_adf53f_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchmembership',
            index=models.Index(fields=['branch', 'is_active'], name='agencies_us_branch__9b6071_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchmembership',
            index=models.Index(fields=['branch_role'], name='agencies_us_branch__1b375a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchmembership',
            index=models.Index(fields=['is_primary'], name='agencies_us_is_prim_834107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbranchmembership',
            unique_together={('user', 'branch')},
        ),
    ]
