# Generated by Django 5.2.12 on 2026-03-04 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('forum_type', models.CharField(choices=[('general', 'General Discussion'), ('strategy', 'Strategy & Planning'), ('governance', 'Governance & Compliance'), ('finance', 'Financial Matters'), ('operations', 'Operations & Performance'), ('risk', 'Risk Management'), ('policy', 'Policy Development'), ('confidential', 'Confidential Matters'), ('committee', 'Committee Specific'), ('emergency', 'Emergency Communications')], default='general', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public - All Board Members'), ('restricted', 'Restricted - Selected Members'), ('confidential', 'Confidential - Board Leadership'), ('private', 'Private - Invite Only')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_moderated', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('allow_polls', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discussion Forums',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('pinned', 'Pinned'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide author identity')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_threads', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='discussions.discussionforum')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('all', 'All Posts'), ('mentions', 'Mentions Only'), ('none', 'No Notifications')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='discussions.discussionthread')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('original', 'Original Post'), ('reply', 'Reply'), ('moderation', 'Moderation Note'), ('system', 'System Message')], default='reply', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edited_reason', models.CharField(blank=True, max_length=200)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('attachments', models.JSONField(blank=True, help_text='List of attached files', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.discussionpost')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='discussions.discussionthread')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('allow_multiple_choices', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='discussions.discussionthread')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('lock_thread', 'Lock Thread'), ('unlock_thread', 'Unlock Thread'), ('pin_thread', 'Pin Thread'), ('unpin_thread', 'Unpin Thread'), ('delete_post', 'Delete Post'), ('edit_post', 'Edit Post'), ('warn_user', 'Warn User'), ('suspend_user', 'Suspend User')], max_length=20)),
                ('reason', models.TextField()),
                ('previous_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_targets', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='discussions.discussionpost')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='discussions.discussionthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='discussions.discussionpoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.discussionpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love'), ('laugh', 'Laugh'), ('angry', 'Angry'), ('sad', 'Sad'), ('wow', 'Wow')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='discussions.discussionpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_threads', to='discussions.discussiontag')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_tags', to='discussions.discussionthread')),
            ],
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['forum', 'status', '-last_activity'], name='discussions_forum_i_2906f9_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['author', '-created_at'], name='discussions_author__bdb7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['priority', '-created_at'], name='discussions_priorit_4c57ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionsubscription',
            unique_together={('user', 'thread')},
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['thread', 'created_at'], name='discussions_thread__e755e9_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['author', '-created_at'], name='discussions_author__6353ce_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['parent', 'order'], name='discussions_parent__52f2f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='threadtag',
            unique_together={('thread', 'tag')},
        ),
    ]
