# Generated by Django 5.2.12 on 2026-04-22 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_externalcalendarconnection_calendarsynclog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='compliance_category',
            field=models.CharField(blank=True, help_text='Compliance category for compliance deadlines', max_length=100),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='governance_type',
            field=models.CharField(blank=True, choices=[('board', 'Board'), ('committee', 'Committee'), ('statutory', 'Statutory'), ('regulatory', 'Regulatory')], help_text='Type of governance event', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Whether attendance/action is mandatory'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=models.CharField(blank=True, help_text='e.g., daily, weekly, monthly, yearly', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before event to send reminder'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendarconfigurator',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('voting_deadline', 'Voting Deadline'), ('document_due', 'Document Due Date'), ('risk_review', 'Risk Review'), ('audit_date', 'Audit Date'), ('committee_meeting', 'Committee Meeting'), ('discussion_event', 'Discussion Event'), ('esignature_deadline', 'E-Signature Deadline'), ('governance_event', 'Governance Event'), ('compliance_deadline', 'Compliance Deadline'), ('policy_expiry', 'Policy Expiry'), ('annual_meeting', 'Annual Meeting'), ('training', 'Training Session'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('voting_deadline', 'Voting Deadline'), ('document_due', 'Document Due Date'), ('risk_review', 'Risk Review'), ('audit_date', 'Audit Date'), ('committee_meeting', 'Committee Meeting'), ('discussion_event', 'Discussion Event'), ('esignature_deadline', 'E-Signature Deadline'), ('governance_event', 'Governance Event'), ('compliance_deadline', 'Compliance Deadline'), ('policy_expiry', 'Policy Expiry'), ('annual_meeting', 'Annual Meeting'), ('training', 'Training Session'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['priority'], name='calendar_ev_priorit_7e4c78_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['compliance_category'], name='calendar_ev_complia_271af2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['governance_type'], name='calendar_ev_governa_cefaaa_idx'),
        ),
    ]
