# Generated by Django 5.2.12 on 2026-03-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('all', 'All Modules'), ('accounts', 'Accounts'), ('meetings', 'Meetings'), ('documents', 'Documents'), ('voting', 'Voting'), ('risk', 'Risk Management'), ('policy', 'Policies'), ('audit', 'Audit Trail'), ('evaluation', 'Board Evaluation'), ('discussions', 'Discussions'), ('system', 'System')], max_length=20, unique=True)),
                ('retention_days', models.IntegerField(help_text='Number of days to retain logs for this module')),
                ('archive_after_days', models.IntegerField(blank=True, help_text='Archive logs after this many days (optional)', null=True)),
                ('auto_cleanup', models.BooleanField(default=True, help_text='Automatically cleanup old logs')),
                ('last_cleanup', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Audit Log Retention Policies',
                'ordering': ['module'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('filters', models.JSONField(blank=True, help_text='Applied filters for the export', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Log Exports',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('export', 'Export'), ('import', 'Import'), ('download', 'Download'), ('upload', 'Upload'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish'), ('archive', 'Archive'), ('restore', 'Restore'), ('acknowledge', 'Acknowledge'), ('vote', 'Vote'), ('comment', 'Comment'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('other', 'Other')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('module', models.CharField(choices=[('accounts', 'Accounts'), ('dashboard', 'Dashboard'), ('meetings', 'Meetings'), ('documents', 'Documents'), ('voting', 'Voting'), ('risk', 'Risk Management'), ('policy', 'Policies'), ('audit', 'Audit Trail'), ('evaluation', 'Board Evaluation'), ('discussions', 'Discussions'), ('system', 'System')], db_index=True, max_length=20)),
                ('description', models.CharField(help_text='Brief description of the action', max_length=500)),
                ('details', models.TextField(blank=True, help_text='Detailed information about the action')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before update', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after update', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data', null=True)),
                ('success', models.BooleanField(default=True, help_text='Was the action successful?')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'module'], name='audit_audit_timesta_3b4a82_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['severity', 'timestamp'], name='audit_audit_severit_4d72db_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx')],
            },
        ),
    ]
