# Generated by Django 5.2.12 on 2026-03-04 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_meeting_virtual_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background', models.TextField(blank=True, help_text='Background information for the motion')),
                ('voting_type', models.CharField(choices=[('simple_majority', 'Simple Majority'), ('qualified_majority', 'Qualified Majority'), ('two_thirds', 'Two-Thirds Majority'), ('unanimous', 'Unanimous'), ('consensus', 'Consensus')], default='simple_majority', max_length=20)),
                ('required_votes', models.PositiveIntegerField(help_text='Number of votes required to pass')),
                ('voting_deadline', models.DateTimeField(help_text='Deadline for voting')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('debate', 'Under Debate'), ('voting', 'Voting Open'), ('passed', 'Passed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn'), ('tabled', 'Tabled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voting_started_at', models.DateTimeField(blank=True, null=True)),
                ('voting_ended_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_motions', to=settings.AUTH_USER_MODEL)),
                ('seconded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seconded_motions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motion',
                'verbose_name_plural': 'Motions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='voting.motion')),
            ],
            options={
                'verbose_name': 'Vote Option',
                'verbose_name_plural': 'Vote Options',
                'ordering': ['order'],
                'unique_together': {('motion', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('yes_votes', models.PositiveIntegerField(default=0)),
                ('no_votes', models.PositiveIntegerField(default=0)),
                ('abstain_votes', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField()),
                ('voting_type', models.CharField(choices=[('simple_majority', 'Simple Majority'), ('qualified_majority', 'Qualified Majority'), ('two_thirds', 'Two-Thirds Majority'), ('unanimous', 'Unanimous'), ('consensus', 'Consensus')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Summary of voting results')),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_results', to=settings.AUTH_USER_MODEL)),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='voting.motion')),
            ],
            options={
                'verbose_name': 'Vote Result',
                'verbose_name_plural': 'Vote Results',
            },
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('eligible_voters', models.ManyToManyField(blank=True, related_name='eligible_sessions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_sessions', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Voting Session',
                'verbose_name_plural': 'Voting Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Optional comment explaining vote')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Vote anonymously (identity hidden from others)')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.motion')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('vote_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='voting.voteoption')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-cast_at'],
                'unique_together': {('motion', 'voter')},
            },
        ),
    ]
