# Generated by Django 5.2.12 on 2026-03-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingaction_alter_meetingattendance_options_and_more'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='allow_anonymous',
            field=models.BooleanField(default=False, help_text='Allow board members to cast anonymous votes on this motion'),
        ),
        migrations.AddField(
            model_name='motion',
            name='category',
            field=models.CharField(choices=[('governance', 'Governance'), ('financial', 'Financial'), ('strategic', 'Strategic'), ('operational', 'Operational'), ('compliance', 'Compliance'), ('personnel', 'Personnel'), ('other', 'Other')], default='governance', max_length=20),
        ),
        migrations.AddField(
            model_name='motion',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='Meeting where this motion was / will be tabled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='motion',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Official motion reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='motion',
            name='result_notes',
            field=models.TextField(blank=True, help_text='Notes on the outcome, recorded by the secretary'),
        ),
        migrations.AddField(
            model_name='motion',
            name='tabled_at',
            field=models.DateTimeField(blank=True, help_text='When the motion was tabled / withdrawn', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='voteoption',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='motions',
            field=models.ManyToManyField(blank=True, help_text='Motions included in this voting session', related_name='sessions', to='voting.motion'),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='background',
            field=models.TextField(blank=True, help_text='Background information and context for the motion'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='required_votes',
            field=models.PositiveIntegerField(help_text='Minimum number of votes required for the result to be valid'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='voting_deadline',
            field=models.DateTimeField(help_text='Deadline for casting votes'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='voting_type',
            field=models.CharField(choices=[('simple_majority', 'Simple Majority (>50%)'), ('qualified_majority', 'Qualified Majority (>60%)'), ('two_thirds', 'Two-Thirds Majority (>66.7%)'), ('unanimous', 'Unanimous'), ('consensus', 'Consensus')], default='simple_majority', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional explanation of vote (not shown if anonymous)'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Hide voter identity from other members (secretary can still see)'),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='voting_type',
            field=models.CharField(choices=[('simple_majority', 'Simple Majority (>50%)'), ('qualified_majority', 'Qualified Majority (>60%)'), ('two_thirds', 'Two-Thirds Majority (>66.7%)'), ('unanimous', 'Unanimous'), ('consensus', 'Consensus')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='motion',
            index=models.Index(fields=['status', '-created_at'], name='voting_moti_status_9a2159_idx'),
        ),
        migrations.AddIndex(
            model_name='motion',
            index=models.Index(fields=['voting_deadline'], name='voting_moti_voting__49b92a_idx'),
        ),
    ]
