# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_deleted_at_user_deleted_by_user_is_deleted_and_more'),
        ('voting', '0006_quorumtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='Restrict voting to members of this committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_sessions', to='accounts.committee'),
        ),
    ]
