# Generated by Django 5.2.12 on 2026-03-04 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Dashboard layout configuration')),
                ('filters_config', models.JSONField(blank=True, default=dict, help_text='Default filters configuration')),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='List of allowed user roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('attendance', 'Meeting Attendance'), ('participation', 'Participation Rate'), ('engagement', 'Engagement Score'), ('documents', 'Document Activity'), ('voting', 'Voting Activity'), ('discussions', 'Discussion Activity'), ('notifications', 'Notification Activity'), ('system_usage', 'System Usage'), ('compliance', 'Compliance Metrics'), ('performance', 'Performance Metrics')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'ordering': ['metric_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('value_text', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context (user_id, meeting_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='analytics.analyticsmetric')),
            ],
            options={
                'verbose_name': 'Analytics Data Point',
                'verbose_name_plural': 'Analytics Data Points',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('meeting_summary', 'Meeting Summary Report'), ('attendance_report', 'Attendance Report'), ('engagement_report', 'Engagement Report'), ('document_usage', 'Document Usage Report'), ('system_performance', 'System Performance Report'), ('compliance_report', 'Compliance Report'), ('custom', 'Custom Report')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Report configuration')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Report data')),
                ('file', models.FileField(blank=True, null=True, upload_to='analytics/reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Report',
                'verbose_name_plural': 'Analytics Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('area_chart', 'Area Chart'), ('metric_card', 'Metric Card'), ('table', 'Data Table'), ('heatmap', 'Heatmap'), ('gauge', 'Gauge Chart')], max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=6)),
                ('height', models.PositiveIntegerField(default=4)),
                ('data_config', models.JSONField(blank=True, default=dict, help_text='Widget data configuration')),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='Chart-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.analyticsdashboard')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticsmetric')),
            ],
            options={
                'verbose_name': 'Analytics Widget',
                'verbose_name_plural': 'Analytics Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='BoardAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', max_length=20)),
                ('total_meetings', models.PositiveIntegerField(default=0)),
                ('total_attendees', models.PositiveIntegerField(default=0)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('document_views', models.PositiveIntegerField(default=0)),
                ('document_downloads', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('voting_participation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_discussions', models.PositiveIntegerField(default=0)),
                ('discussion_participation', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('system_uptime', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Detailed metrics data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Board Analytics Snapshot',
                'verbose_name_plural': 'Board Analytics Snapshots',
                'ordering': ['-snapshot_date', '-snapshot_type'],
                'indexes': [models.Index(fields=['snapshot_date', 'snapshot_type'], name='analytics_b_snapsho_23240d_idx')],
                'unique_together': {('snapshot_date', 'snapshot_type')},
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meeting_participation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('document_engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discussion_participation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meetings_attended', models.PositiveIntegerField(default=0)),
                ('documents_viewed', models.PositiveIntegerField(default=0)),
                ('votes_cast', models.PositiveIntegerField(default=0)),
                ('discussions_started', models.PositiveIntegerField(default=0)),
                ('comments_made', models.PositiveIntegerField(default=0)),
                ('total_time_online', models.PositiveIntegerField(default=0, help_text='Total time online in minutes')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('dashboard_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics Profile',
                'verbose_name_plural': 'User Analytics Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_type', 'is_active'], name='analytics_a_metric__9ff734_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['frequency', 'is_active'], name='analytics_a_frequen_e5e100_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdatapoint',
            index=models.Index(fields=['metric', '-timestamp'], name='analytics_a_metric__20b5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdatapoint',
            index=models.Index(fields=['timestamp'], name='analytics_a_timesta_6bf371_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdatapoint',
            index=models.Index(fields=['metric', 'timestamp'], name='analytics_a_metric__6d3772_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', '-created_at'], name='analytics_a_report__6da31a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['status'], name='analytics_a_status_8de32c_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticsprofile',
            index=models.Index(fields=['-overall_engagement_score'], name='analytics_u_overall_3b66df_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticsprofile',
            index=models.Index(fields=['last_activity'], name='analytics_u_last_ac_1dd9f0_idx'),
        ),
    ]
