# Generated by Django 5.2.12 on 2026-04-22 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_attendanceanalytics_compliancescorecard_customreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdashboard',
            options={'ordering': ['dashboard_type', 'name'], 'verbose_name': 'Analytics Dashboard', 'verbose_name_plural': 'Analytics Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='analyticsmetric',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Analytics Metric', 'verbose_name_plural': 'Analytics Metrics'},
        ),
        migrations.AlterModelOptions(
            name='analyticswidget',
            options={'ordering': ['-is_pinned', 'position_y', 'position_x'], 'verbose_name': 'Analytics Widget', 'verbose_name_plural': 'Analytics Widgets'},
        ),
        migrations.AddField(
            model_name='analyticsdashboard',
            name='auto_refresh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsdashboard',
            name='auto_refresh_interval',
            field=models.PositiveIntegerField(default=300, help_text='Auto-refresh interval in seconds'),
        ),
        migrations.AddField(
            model_name='analyticsdashboard',
            name='dashboard_type',
            field=models.CharField(choices=[('governance', 'Governance Dashboard'), ('financial', 'Financial Dashboard'), ('operational', 'Operational Dashboard'), ('compliance', 'Compliance Dashboard'), ('risk', 'Risk Dashboard'), ('performance', 'Performance Dashboard'), ('custom', 'Custom Dashboard')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsdashboard',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is a default dashboard for the type'),
        ),
        migrations.AddField(
            model_name='analyticsmetric',
            name='category',
            field=models.CharField(choices=[('governance', 'Governance'), ('financial', 'Financial'), ('operational', 'Operational'), ('compliance', 'Compliance'), ('risk', 'Risk'), ('performance', 'Performance'), ('meetings', 'Meetings')], default='governance', max_length=50),
        ),
        migrations.AddField(
            model_name='analyticsmetric',
            name='data_type',
            field=models.CharField(choices=[('count', 'Count'), ('percentage', 'Percentage'), ('currency', 'Currency'), ('number', 'Number'), ('ratio', 'Ratio'), ('score', 'Score')], default='number', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsmetric',
            name='key',
            field=models.CharField(default='', help_text='Unique key for the metric', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='analyticsmetric',
            name='visualization_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('gauge', 'Gauge'), ('number', 'Number Display'), ('table', 'Table')], default='line', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticswidget',
            name='insight_config',
            field=models.JSONField(blank=True, default=dict, help_text='Insight configuration'),
        ),
        migrations.AddField(
            model_name='analyticswidget',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin widget to top of dashboard'),
        ),
        migrations.AddField(
            model_name='analyticswidget',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analyticswidget',
            name='show_insights',
            field=models.BooleanField(default=True, help_text='Show AI-generated insights'),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='metric_type',
            field=models.CharField(choices=[('attendance', 'Meeting Attendance'), ('participation', 'Participation Rate'), ('engagement', 'Engagement Score'), ('documents', 'Document Activity'), ('voting', 'Voting Activity'), ('discussions', 'Discussion Activity'), ('notifications', 'Notification Activity'), ('system_usage', 'System Usage'), ('compliance', 'Compliance Metrics'), ('performance', 'Performance Metrics'), ('governance', 'Governance Metrics'), ('financial', 'Financial Metrics'), ('operational', 'Operational Metrics'), ('risk', 'Risk Metrics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analyticswidget',
            name='widget_type',
            field=models.CharField(choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('area_chart', 'Area Chart'), ('metric_card', 'Metric Card'), ('table', 'Data Table'), ('heatmap', 'Heatmap'), ('gauge', 'Gauge Chart'), ('trend', 'Trend Indicator'), ('kpi_card', 'KPI Card')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['dashboard_type'], name='analytics_a_dashboa_7dd606_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['is_default'], name='analytics_a_is_defa_a44dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['is_public'], name='analytics_a_is_publ_d2c104_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['key'], name='analytics_a_key_bfee62_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['category', 'is_active'], name='analytics_a_categor_878149_idx'),
        ),
    ]
