# Generated by Django 5.2.12 on 2026-03-04 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('probability', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=10)),
                ('risk_score', models.PositiveIntegerField(default=1, help_text='Calculated risk score (1-25)')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessed', 'Assessed'), ('mitigated', 'Mitigated'), ('monitored', 'Monitored'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='identified', max_length=20)),
                ('potential_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Potential financial impact in USD', max_digits=12, null=True)),
                ('potential_impact_description', models.TextField(blank=True)),
                ('identified_date', models.DateField(default=django.utils.timezone.now)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('actual_resolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_risks', to=settings.AUTH_USER_MODEL)),
                ('risk_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('detailed', 'Detailed Assessment'), ('periodic', 'Periodic Review'), ('incident', 'Post-Incident Assessment')], default='initial', max_length=20)),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('root_causes', models.TextField(blank=True, help_text='Identified root causes')),
                ('impact_analysis', models.TextField(blank=True, help_text='Detailed impact analysis')),
                ('vulnerability_analysis', models.TextField(blank=True, help_text='Vulnerability assessment')),
                ('existing_controls', models.TextField(blank=True, help_text='Current controls in place')),
                ('control_effectiveness', models.TextField(blank=True, help_text='Effectiveness of existing controls')),
                ('impact_probability', models.DecimalField(blank=True, decimal_places=2, help_text='Impact probability (0-1)', max_digits=5, null=True)),
                ('impact_severity', models.DecimalField(blank=True, decimal_places=2, help_text='Impact severity (0-1)', max_digits=5, null=True)),
                ('recommended_actions', models.TextField(blank=True, help_text='Recommended actions')),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk.risk')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('strategic', 'Strategic Risk'), ('operational', 'Operational Risk'), ('financial', 'Financial Risk'), ('compliance', 'Compliance Risk'), ('reputational', 'Reputational Risk'), ('cybersecurity', 'Cybersecurity Risk'), ('market', 'Market Risk'), ('regulatory', 'Regulatory Risk'), ('environmental', 'Environmental Risk'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='risk.riskcategory')),
            ],
            options={
                'verbose_name': 'Risk Category',
                'verbose_name_plural': 'Risk Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk.riskcategory'),
        ),
        migrations.CreateModel(
            name='RiskIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('actual_impact', models.TextField(blank=True)),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('response_team', models.ManyToManyField(blank=True, related_name='incident_responses', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='risk.risk')),
            ],
            options={
                'verbose_name': 'Risk Incident',
                'verbose_name_plural': 'Risk Incidents',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitigation_type', models.CharField(choices=[('accept', 'Accept Risk'), ('avoid', 'Avoid Risk'), ('transfer', 'Transfer Risk'), ('mitigate', 'Mitigate Risk'), ('monitor', 'Monitor Only')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('effective', 'Effective'), ('ineffective', 'Ineffective'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resources_required', models.TextField(blank=True)),
                ('effectiveness_rating', models.PositiveIntegerField(blank=True, help_text='Effectiveness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('effectiveness_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigations', to='risk.riskassessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mitigations', to=settings.AUTH_USER_MODEL)),
                ('responsible_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='risk.risk')),
            ],
            options={
                'verbose_name': 'Risk Mitigation',
                'verbose_name_plural': 'Risk Mitigations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitoring_type', models.CharField(choices=[('regular', 'Regular Review'), ('incident', 'Incident Review'), ('audit', 'Audit Review'), ('escalation', 'Escalation Review')], default='regular', max_length=20)),
                ('monitoring_date', models.DateField(default=django.utils.timezone.now)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('current_status', models.TextField(help_text='Current risk status and developments')),
                ('risk_score_change', models.IntegerField(default=0, help_text='Change in risk score (+/-)')),
                ('new_risk_score', models.PositiveIntegerField(help_text='Updated risk score')),
                ('actions_taken', models.TextField(blank=True)),
                ('effectiveness_assessment', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('escalation_required', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_monitoring', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='reviewed_monitoring', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='risk.risk')),
            ],
            options={
                'verbose_name': 'Risk Monitoring',
                'verbose_name_plural': 'Risk Monitoring',
                'ordering': ['-monitoring_date'],
            },
        ),
    ]
