# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_retentionpolicy_archiverecord_and_more'),
        ('meetings', '0011_meetingattendance_attendee_source_and_more'),
        ('risk', '0006_boardevaluation_directorevaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('compliance_attendance', 'Compliance Attendance'), ('policy_review', 'Policy Review'), ('risk_assessment', 'Risk Assessment'), ('audit_report', 'Audit Report'), ('annual_meeting', 'Annual Meeting'), ('other', 'Other')], max_length=30)),
                ('original_record_id', models.UUIDField(help_text='ID of the original record before archiving')),
                ('record_title', models.CharField(help_text='Title or description of the archived record', max_length=255)),
                ('compliance_category', models.CharField(blank=True, help_text='Category of compliance', max_length=100)),
                ('compliance_period_start', models.DateField(blank=True, null=True)),
                ('compliance_period_end', models.DateField(blank=True, null=True)),
                ('archived_data', models.JSONField(default=dict, help_text='Snapshot of record data at archiving time')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True, help_text='Reason for archiving')),
                ('retention_period_years', models.PositiveIntegerField(default=7, help_text='Years to retain this archive')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this archive can be permanently deleted', null=True)),
                ('archive_status', models.CharField(choices=[('archived', 'Archived'), ('restored', 'Restored'), ('expired', 'Expired'), ('permanently_deleted', 'Permanently Deleted')], default='archived', max_length=30)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_compliance_records', to=settings.AUTH_USER_MODEL)),
                ('related_documents', models.ManyToManyField(blank=True, related_name='compliance_archives', to='documents.document')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Archive',
                'verbose_name_plural': 'Compliance Archives',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['record_type'], name='risk_compli_record__d9f2f6_idx'), models.Index(fields=['archived_at'], name='risk_compli_archive_fa132f_idx'), models.Index(fields=['expires_at'], name='risk_compli_expires_be0fe6_idx'), models.Index(fields=['archive_status'], name='risk_compli_archive_bcfb5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_type', models.CharField(choices=[('statutory', 'Statutory Meeting'), ('board', 'Board Meeting'), ('committee', 'Committee Meeting'), ('training', 'Compliance Training'), ('audit', 'Audit Meeting'), ('risk', 'Risk Committee Meeting'), ('other', 'Other Compliance Event')], default='board', max_length=20)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late'), ('remote', 'Remote/Video')], default='present', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of attendance in minutes', null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('excuse_reason', models.TextField(blank=True, help_text='Reason for absence if excused')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Who approved the excuse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_excuses', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_attendance', to='meetings.meeting')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_compliance_attendance', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Attendance',
                'verbose_name_plural': 'Compliance Attendance Records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='risk_compli_user_id_c02899_idx'), models.Index(fields=['meeting'], name='risk_compli_meeting_b5192d_idx'), models.Index(fields=['compliance_type'], name='risk_compli_complia_58ebc0_idx'), models.Index(fields=['attendance_status'], name='risk_compli_attenda_09f1e1_idx')],
                'unique_together': {('user', 'meeting')},
            },
        ),
    ]
