# Generated by Django 5.2.12 on 2026-03-04 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('board', 'Board Meeting'), ('committee', 'Committee Meeting'), ('agm', 'Annual General Meeting'), ('emergency', 'Emergency Meeting'), ('workshop', 'Workshop/Training')], default='board', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('scheduled_end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('virtual_meeting_url', models.URLField(blank=True, help_text='Virtual meeting link (Zoom, Teams, etc.)')),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meeting_attendees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('required_attendees', models.ManyToManyField(blank=True, related_name='required_meeting_attendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.PositiveIntegerField(default=15, help_text='Estimated duration in minutes')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='meetings/agenda_attachments/')),
                ('is_discussed', models.BooleanField(default=False)),
                ('decision', models.TextField(blank=True, help_text='Decision made on this agenda item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agenda', to=settings.AUTH_USER_MODEL)),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_agenda', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Agenda Item',
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Full meeting minutes content')),
                ('action_items', models.TextField(blank=True, help_text='Action items and assignments')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='meetings/minutes/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL)),
                ('drafted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_minutes', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='meetings.meeting')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_minutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
                'verbose_name_plural': 'Meeting Minutes',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent'), ('apologies', 'Absent with Apologies'), ('no_response', 'No Response')], default='no_response', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reason for absence or additional notes')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='meetings.meeting')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendance',
                'ordering': ['meeting', 'attendee'],
                'unique_together': {('meeting', 'attendee')},
            },
        ),
    ]
