# Generated by Django 5.2.12 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='virtual_platform',
            field=models.CharField(blank=True, choices=[('', 'No Virtual Meeting'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('skype', 'Skype'), ('other', 'Other Platform')], default='', help_text='Virtual meeting platform', max_length=50),
        ),
    ]
