# Generated by Django 5.2.12 on 2026-03-04 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_virtual_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConferenceParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Participant email', max_length=254)),
                ('display_name', models.CharField(help_text='Display name in meeting', max_length=200)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('presenter', 'Presenter'), ('attendee', 'Attendee'), ('panelist', 'Panelist')], default='attendee', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('platform_participant_id', models.CharField(blank=True, help_text='Platform participant ID', max_length=200)),
                ('platform_data', models.JSONField(blank=True, default=dict)),
                ('attended', models.BooleanField(default=False)),
                ('was_recording', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Conference Participant',
                'verbose_name_plural': 'Video Conference Participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoConferenceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('available', 'Available'), ('failed', 'Failed'), ('expired', 'Expired')], default='processing', max_length=20)),
                ('file_url', models.URLField(help_text='Recording URL')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Recording duration in seconds')),
                ('format', models.CharField(default='mp4', help_text='Video format', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Make recording publicly accessible')),
                ('access_password', models.CharField(blank=True, help_text='Password for private recordings', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Recording expiration date', null=True)),
                ('platform_recording_id', models.CharField(blank=True, help_text='Platform recording ID', max_length=200)),
                ('platform_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Conference Recording',
                'verbose_name_plural': 'Video Conference Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoConferenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Platform session ID', max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('', 'No Virtual Meeting'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('skype', 'Skype'), ('jitsi', 'Jitsi Meet'), ('whereby', 'Whereby'), ('other', 'Other Platform')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('peak_participants', models.PositiveIntegerField(default=0)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('recording_ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('platform_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Conference Session',
                'verbose_name_plural': 'Video Conference Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_breakout_rooms',
            field=models.BooleanField(default=False, help_text='Enable breakout rooms'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_chat',
            field=models.BooleanField(default=True, help_text='Enable meeting chat'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_recording',
            field=models.BooleanField(default=False, help_text='Record the meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_screen_sharing',
            field=models.BooleanField(default=True, help_text='Enable screen sharing'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_waiting_room',
            field=models.BooleanField(default=True, help_text='Enable waiting room'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Enable virtual meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum participants (leave unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific data (API responses, etc.)'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Recording duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Recording URL after meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='virtual_dial_in',
            field=models.CharField(blank=True, help_text='Dial-in phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='virtual_meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID/Room ID', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='virtual_meeting_password',
            field=models.CharField(blank=True, help_text='Meeting password', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location (leave blank for virtual only)', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='virtual_meeting_url',
            field=models.URLField(blank=True, help_text='Virtual meeting link'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='virtual_platform',
            field=models.CharField(blank=True, choices=[('', 'No Virtual Meeting'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('skype', 'Skype'), ('jitsi', 'Jitsi Meet'), ('whereby', 'Whereby'), ('other', 'Other Platform')], default='', help_text='Virtual meeting platform', max_length=50),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_date', 'status'], name='meetings_me_schedul_6f5326_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['virtual_platform'], name='meetings_me_virtual_371cae_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', '-scheduled_date'], name='meetings_me_organiz_857c54_idx'),
        ),
        migrations.AddField(
            model_name='videoconferenceparticipant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoconferencerecording',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='videoconferencesession',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='videoconferencerecording',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.videoconferencesession'),
        ),
        migrations.AddField(
            model_name='videoconferenceparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.videoconferencesession'),
        ),
        migrations.AddIndex(
            model_name='videoconferencesession',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_vi_meeting_315cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferencesession',
            index=models.Index(fields=['platform', 'status'], name='meetings_vi_platfor_ab0905_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferencerecording',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_vi_meeting_8f8f89_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferencerecording',
            index=models.Index(fields=['session', '-created_at'], name='meetings_vi_session_0246e9_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferencerecording',
            index=models.Index(fields=['status'], name='meetings_vi_status_bbac09_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferenceparticipant',
            index=models.Index(fields=['session', '-joined_at'], name='meetings_vi_session_2c1d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='videoconferenceparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='meetings_vi_user_id_603647_idx'),
        ),
    ]
