# Generated by Django 5.2.12 on 2026-03-11 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('meetings', '0003_videoconferenceparticipant_videoconferencerecording_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting Action',
                'verbose_name_plural': 'Meeting Actions',
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='meetingattendance',
            options={'ordering': ['meeting', 'attendee__first_name'], 'verbose_name': 'Meeting Attendance', 'verbose_name_plural': 'Meeting Attendance'},
        ),
        migrations.RemoveIndex(
            model_name='videoconferencerecording',
            name='meetings_vi_session_0246e9_idx',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='action_due_date',
            field=models.DateField(blank=True, help_text='Due date for follow-up action', null=True),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='action_owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for any follow-up action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_agenda_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='item_type',
            field=models.CharField(choices=[('information', 'Information'), ('discussion', 'Discussion'), ('decision', 'Decision / Resolution'), ('action', 'Action Item'), ('presentation', 'Presentation'), ('aob', 'Any Other Business')], default='discussion', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this meeting belongs to (leave blank for organisation-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='agencies.branch'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='Committee this meeting is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='agencies.committee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='invitations_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='quorum_required',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum attendees required for quorum', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='quorum_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('quorum_met', 'Quorum Met'), ('quorum_not_met', 'Quorum Not Met')], default='not_checked', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Official meeting reference / serial number', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent_1h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone_display',
            field=models.CharField(blank=True, default='Africa/Nairobi', help_text='Timezone shown to attendees', max_length=60),
        ),
        migrations.AddField(
            model_name='meeting',
            name='venue_notes',
            field=models.TextField(blank=True, help_text='Directions, parking, access instructions, etc.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='virtual_host_key',
            field=models.CharField(blank=True, help_text='Host key (confidential — only shown to organiser)', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='rsvp_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='rsvp_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='decisions',
            field=models.TextField(blank=True, help_text='Key decisions made'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='next_meeting_date',
            field=models.DateTimeField(blank=True, help_text='Date of next meeting (if agreed)', null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agenda_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='decision',
            field=models.TextField(blank=True, help_text='Decision made on this item'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_agenda_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, help_text='High-level agenda overview'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enable_breakout_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enable_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enable_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enable_screen_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enable_waiting_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Enable virtual / hybrid meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or venue (leave blank for virtual-only)', max_length=300),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum participants (leave blank for unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('board', 'Board Meeting'), ('committee', 'Committee Meeting'), ('agm', 'Annual General Meeting'), ('emergency', 'Emergency Meeting'), ('workshop', 'Workshop / Training'), ('extraordinary', 'Extraordinary General Meeting')], default='board', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='virtual_dial_in',
            field=models.CharField(blank=True, help_text='Dial-in phone number(s)', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='virtual_meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID / Room ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='virtual_meeting_password',
            field=models.CharField(blank=True, help_text='Meeting password (if any)', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent'), ('apologies', 'Absent with Apologies'), ('late', 'Attended (Late)'), ('partial', 'Partial Attendance'), ('no_response', 'No Response')], default='no_response', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='content',
            field=models.TextField(help_text='Full meeting minutes'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoconferenceparticipant',
            name='display_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoconferenceparticipant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='videoconferenceparticipant',
            name='platform_participant_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='access_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='duration_seconds',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='file_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='format',
            field=models.CharField(default='mp4', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoconferencerecording',
            name='platform_recording_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'status'], name='meetings_me_meeting_79d58b_idx'),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='meetings.agendaitem'),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meeting_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingaction',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meetings.meeting'),
        ),
    ]
