# Generated by Django 5.2.12 on 2026-04-22 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_branch_country_and_more'),
        ('documents', '0003_retentionpolicy_archiverecord_and_more'),
        ('meetings', '0010_boardpack_boardpackaccesslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='attendee_source',
            field=models.CharField(choices=[('required', 'Required Attendee'), ('committee', 'Committee Member'), ('manual', 'Manually Added'), ('invitation', 'Invited Guest')], default='manual', help_text='How this attendee was added to the meeting', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='archive_date',
            field=models.DateTimeField(blank=True, help_text='Date when minutes were archived', null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether these minutes have been archived'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='retention_period_years',
            field=models.PositiveIntegerField(default=7, help_text='Years to retain these minutes before archiving'),
        ),
        migrations.CreateModel(
            name='AnnualMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='Fiscal year for this annual meeting')),
                ('statutory_requirements', models.TextField(blank=True, help_text='Statutory requirements for this annual meeting')),
                ('requirements_met', models.TextField(blank=True, help_text='Documentation of requirements that were met')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('pending', 'Pending Review'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('compliance_notes', models.TextField(blank=True, help_text='Notes on compliance status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('required_by_date', models.DateField(blank=True, help_text='Date by which annual meeting must be held', null=True)),
                ('actual_date', models.DateField(blank=True, help_text='Actual date when annual meeting was held', null=True)),
                ('resolutions_passed', models.TextField(blank=True, help_text='Summary of resolutions passed')),
                ('key_decisions', models.TextField(blank=True, help_text='Key decisions made during the meeting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_attendees', models.ManyToManyField(blank=True, help_text='Actual attendees', related_name='attended_annual_meetings', to=settings.AUTH_USER_MODEL)),
                ('audit_report', models.ForeignKey(blank=True, help_text='Audit report for this annual meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_meeting_audits', to='documents.document')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_meetings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, help_text='The actual meeting record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_meeting_record', to='meetings.meeting')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization/Branch this annual meeting belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_meetings', to='agencies.branch')),
                ('required_attendees', models.ManyToManyField(blank=True, help_text='Attendees required for compliance', related_name='required_annual_meetings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Who reviewed the compliance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_annual_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual Meeting',
                'verbose_name_plural': 'Annual Meetings',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['year'], name='meetings_an_year_61a835_idx'), models.Index(fields=['organization'], name='meetings_an_organiz_953cff_idx'), models.Index(fields=['compliance_status'], name='meetings_an_complia_e9e427_idx'), models.Index(fields=['required_by_date'], name='meetings_an_require_6cd078_idx')],
                'unique_together': {('year', 'organization')},
            },
        ),
    ]
