# Generated by Django 5.2.12 on 2026-03-04 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('channel_type', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('meeting_reminder', 'Meeting Reminder'), ('meeting_update', 'Meeting Update'), ('voting_open', 'Voting Open'), ('voting_close', 'Voting Closing'), ('voting_result', 'Voting Result'), ('document_shared', 'Document Shared'), ('document_updated', 'Document Updated'), ('policy_update', 'Policy Update'), ('risk_alert', 'Risk Alert'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Discussion Mention'), ('audit_alert', 'Audit Alert'), ('system_update', 'System Update'), ('security_alert', 'Security Alert')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('default_action_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('meeting_reminder', 'Meeting Reminder'), ('meeting_update', 'Meeting Update'), ('voting_open', 'Voting Open'), ('voting_close', 'Voting Closing'), ('voting_result', 'Voting Result'), ('document_shared', 'Document Shared'), ('document_updated', 'Document Updated'), ('policy_update', 'Policy Update'), ('risk_alert', 'Risk Alert'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Discussion Mention'), ('audit_alert', 'Audit Alert'), ('system_update', 'System Update'), ('security_alert', 'Security Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('meeting_reminder', 'Meeting Reminder'), ('meeting_update', 'Meeting Update'), ('voting_open', 'Voting Open'), ('voting_close', 'Voting Closing'), ('voting_result', 'Voting Result'), ('document_shared', 'Document Shared'), ('document_updated', 'Document Updated'), ('policy_update', 'Policy Update'), ('risk_alert', 'Risk Alert'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Discussion Mention'), ('audit_alert', 'Audit Alert'), ('system_update', 'System Update'), ('security_alert', 'Security Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='batch_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationchannel')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_meeting_reminders', models.BooleanField(default=True)),
                ('email_voting_notifications', models.BooleanField(default=True)),
                ('email_document_updates', models.BooleanField(default=True)),
                ('email_discussion_replies', models.BooleanField(default=True)),
                ('email_risk_alerts', models.BooleanField(default=True)),
                ('email_audit_alerts', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=False)),
                ('in_app_meeting_reminders', models.BooleanField(default=True)),
                ('in_app_voting_notifications', models.BooleanField(default=True)),
                ('in_app_document_updates', models.BooleanField(default=True)),
                ('in_app_discussion_replies', models.BooleanField(default=True)),
                ('in_app_risk_alerts', models.BooleanField(default=True)),
                ('in_app_audit_alerts', models.BooleanField(default=True)),
                ('in_app_system_updates', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='immediate', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx'),
        ),
    ]
